all: daysCalculatorA daysCalculatorB daysCalculatorC daysCalculatorD daysCalculatorE

daysCalculatorA: daysCalculatorA.c
	gcc -ansi -Wall -o daysCalculatorA daysCalculatorA.c

daysCalculatorB: daysCalculatorB.c
	gcc -ansi -Wall -o daysCalculatorB daysCalculatorB.c

daysCalculatorC: daysCalculatorC.c
	gcc -ansi -Wall -o daysCalculatorC daysCalculatorC.c

daysCalculatorD: daysCalculatorD.c
	gcc -ansi -Wall -o daysCalculatorD daysCalculatorD.c

daysCalculatorE: daysCalculatorE.c
	gcc -ansi -Wall -o daysCalculatorE daysCalculatorE.c

clean:
	rm daysCalculatorA daysCalculatorB daysCalculatorC daysCalculatorD daysCalculatorE
